#!/bin/sh

INTERFACE="${1}"
SOURCEIPADDRESS="${2}"
DESTINATIONPORTNUMBER="${3}"
TARGETIPADDRESS="${4}"
TARGETPORTNUMBER="${5}"

iptables -A PREROUTING -t nat -i "${INTERFACE}" -p tcp -s "${SOURCEIPADDRESS}" --dport "${DESTINATIONPORTNUMBER}" -j DNAT --to "${TARGETIPADDRESS}:${TARGETPORTNUMBER}"
#iptables -A PREROUTING -t nat -i "${INTERFACE}" -p tcp --dport "${DESTINATIONPORTNUMBER}" -j DNAT --to "${TARGETIPADDRESS}:${TARGETPORTNUMBER}"
iptables -A FORWARD -p tcp -d "${TARGETIPADDRESS}" --dport "${TARGETPORTNUMBER}" -j ACCEPT
